export const TRACKS_FETCHED = 'TRACKS_FETCHED'
export const SET_ACTIVE_TRACK = 'SET_ACTIVE_TRACK'
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
export const ADD_SEARCH_TERM_HISTORY = 'ADD_SEARCH_TERM_HISTORY'